### ISSUE TITLE
vim Bindings do not work in the binary

### ISSUE THREAD

**Issue by dderjoel** [namhyung/das#3]
when pressing j/k the line is not moving. 
I installed from the binary as advertised in the README.md
achlinux;  5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000 x86_64 GNU/Linux
I looked at the code, and there is apparently code to to that.
https://github.com/namhyung/das/blob/master/tui.go#L764

I am trying to compile it locally, but there are errors.
1. Apparently, it needs capstone to be installed. (cannot find capstone/capstone.h) (fair. installed it)
1. then it complains: in bnagy/gapstone/arm_64_constants.go "could not determine kind of name for C.ARM64_[]" but I think the problem is in gapstone itself. -> I'd like to have a list of dependencies in this repo anyway.

So I think the vim bindings should be mentioned in the README.
And they should work in the binary.

Would be happy to contribute, if necessary, (Mostly about more vim-like-user-experience).

**Comment by namhyung** [comment]
Thanks for using das and reporting the issue.  The released binary (v0.1) is quite old and predates when the j/k key binding was added.  I need to update it with a recent version.  I thought some features want to add but have been failing to have time to work on them.

The capstone integration is to support multi-arch smoothly (without using objdump).  But it's not mature yet so I think default build should not depend on the capstone.  But I'm not familiar with the Go build system yet - if you can contribute this, it'd be really great!

Also feel free to send a PR to update documentation and adding vim-like features. :)

**Comment by dderjoel** [comment]
well, I have never programmed in Go so far, but this is a good opportunity to learn.
Can you remember, from which commit the binary is?

Ill have a look to compile the current master and see what the issues are. Can you currently build master?

**Comment by namhyung** [comment]
I don't want to push you and asked it assuming you have some experience of Go.

I'm able to build the master on my dev machine (debian based one).

**Comment by namhyung** [comment]
v0.2 is released and it does not require gapstone by default.

**Comment by dderjoel** [comment]
Thanks, I can confirm, that it now works out of the box!
